# Example: Complete Terraform CI Pipeline
#
# This workflow demonstrates the full CI pipeline using terraform-ci.yml for
# validation, tfsec + Trivy scans, SARIF uploads, and signed plan artifacts.
#
# Use this for: Post-merge validation or protected branch builds
# Estimated time: ~4-6 minutes (parallel security scans)

name: Terraform CI Pipeline

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'env/**'
      - 'modules/**'
      - '**.tf'
      - '**.tfvars'
  
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        type: choice
        options:
          - dev
          - stage
          - prod
        default: dev
      terraform-version:
        description: 'Terraform version'
        type: string
        default: '1.7.0'

# Required permissions for full CI workflow
permissions:
  contents: read          # Checkout code
  security-events: write  # Upload SARIF to Security tab
  id-token: write         # Azure OIDC authentication
  pull-requests: write    # Comment on PRs
  actions: read           # SARIF upload telemetry
  attestations: write     # Sign plan artifacts

jobs:
  # ============================================================================
  # Determine which environment to target based on branch or manual input
  # ============================================================================
  prepare:
    name: Determine Environment
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.detect.outputs.environment }}
      working-directory: ${{ steps.detect.outputs.working-directory }}
    
    steps:
      - uses: paloitmbb/mbb-tf-actions/actions/determine-environment@main
        id: detect
        with:
          manual-environment: ${{ github.event.inputs.environment || '' }}
          fallback-environment: ${{ github.ref == 'refs/heads/main' && 'prod' || github.ref == 'refs/heads/develop' && 'stage' || 'dev' }}
          working-directory-prefix: './env'

  # ============================================================================
  # Run complete Terraform CI pipeline
  # ============================================================================
  terraform-ci:
    name: Terraform CI (${{ needs.prepare.outputs.environment }})
    needs: prepare
    uses: paloitmbb/mbb-tf-workflows/.github/workflows/terraform-ci.yml@main
    with:
      # Terraform Configuration
      terraform-version: ${{ github.event.inputs.terraform-version || '1.7.0' }}
      working-directory: ${{ needs.prepare.outputs.working-directory }}
      environment: ${{ needs.prepare.outputs.environment }}
      terraform-var-file: 'terraform.tfvars'
      
      # Code Quality
      enable-tflint: true
      tflint-version: 'v0.60.0'
      
      # Security Scanners (tfsec + Trivy in parallel)
      enable-tfsec: true
      enable-trivy: true
      
      # Security Severity Thresholds (HIGH by default)
      tfsec-severity: 'HIGH'
      trivy-severity: 'HIGH'
      
      # Continue-on-error Control
      tfsec-continue-on-error: true        # Allow all scans to run
      trivy-continue-on-error: true        # Full security posture
      aggregate-continue-on-error: false   # Fail fast if aggregate fails
      
      # Execution Configuration
      runner-os: 'ubuntu-latest'
      timeout-minutes: 60
    
    secrets:
      # Azure OIDC Authentication (required for plan generation)
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      # Optional: GitHub token for private module access
      # GH_TOKEN: ${{ secrets.GH_TOKEN }}

  # ============================================================================
  # Optional: Post-CI notification or downstream job
  # ============================================================================
  notify:
    name: Notify on Changes
    needs: [prepare, terraform-ci]
    runs-on: ubuntu-latest
    if: always() && needs.terraform-ci.outputs.plan-exitcode == '2'
    
    steps:
      - name: Notify Team
        run: |
          echo "## 🚀 Infrastructure Changes Detected" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Environment:** ${{ needs.prepare.outputs.environment }}" >> $GITHUB_STEP_SUMMARY
          echo "**Plan Artifact:** ${{ needs.terraform-ci.outputs.plan-artifact-name }}" >> $GITHUB_STEP_SUMMARY
          echo "**Plan Hash:** ${{ needs.terraform-ci.outputs.plan-hash }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Review the plan artifact before applying changes." >> $GITHUB_STEP_SUMMARY
